version: '3.8'  

services:  
  postgres:  
    image: postgres:13  
    environment:  
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: securepassword  
      POSTGRES_DB: traffic_db  
    ports:  
      - "5432:5432"  
    volumes:  
      - pgdata:/var/lib/postgresql/data  

  redis:  
    image: redis:6  
    ports:  
      - "6379:6379"  

  ml_service:  
    build: ./data_processing  
    command: python -m ml_models.lstm_model  
    depends_on:  
      - postgres  
      - redis  

  dashboard:  
    build: ./user_interface/dashboard  
    ports:  
      - "5000:5000"  
    environment:  
      FLASK_ENV: development  

volumes:  
  pgdata:  