version: '3.8'  

services:  
  web:  
    build: .  
    ports:  
      - "5000:5000"  
    environment:  
      - FLASK_ENV=production  
    depends_on:  
      - redis  
      - postgres  

  postgres:  
    image: postgres:13  
    environment:  
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: securepassword  
      POSTGRES_DB: traffic_db  
    volumes:  
      - postgres_data:/var/lib/postgresql/data  

  redis:  
    image: redis:6  
    ports:  
      - "6379:6379"  

volumes:  
  postgres_data:  