# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-system
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: app
        image: your-docker-image
        ports:
        - containerPort: 5000