database:  
  postgres:  
    host: localhost  
    port: 5432  
    name: traffic_db  
    user: admin  
    password: securepassword  
  redis:  
    host: localhost  
    port: 6379  

apis:  
    osrm: "http://router.project-osrm.org"  
    google_maps: "API_KEY_HERE"  

ml_models:  
    lstm_weights: "models/lstm_weights.h5"   